name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Allows manual triggering
permissions:
  contents: write # To write the generated contents to the README
jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: https://neilpatel.com/blog/feed/

